apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycollector
  template:
    metadata:
      name: mycollector
      labels:
        app: mycollector
    spec:
      containers:
      - name : collector
        image: myapp3
        imagePullPolicy: Never
        env:
        - name: HOST
          value: "kafka.kafka-ca1"
        resources:
          limits:
            cpu: 300m
            memory: 20Mi
          requests:
            cpu: 200m
            memory: 10Mi
